"""add firt_name  field

Revision ID: 219c1bea445a
Revises: f102f6a7a651
Create Date: 2026-03-06 12:21:59.846257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '219c1bea445a'
down_revision: Union[str, Sequence[str], None] = 'f102f6a7a651'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('firt_name', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'firt_name')
    # ### end Alembic commands ###
